version: '3.7'

services:

  elections:
    build:
      context: ./services/elections
      dockerfile: Dockerfile-dev
    volumes:
      - './services/elections:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/elections_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/elections_test
    depends_on:
      - elections-db

  elections-db:
    build:
      context: ./services/elections/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  states:
    build:
      context: ./services/states
      dockerfile: Dockerfile-dev
    volumes:
      - './services/states:/usr/src/app'
    ports:
      - 5003:5002
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/states_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/states_test
    depends_on:
      - states-db

  states-db:
    build:
      context: ./services/states/project/db
      dockerfile: Dockerfile
    ports:
      - 5436:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
