version: '3.7'

services:

  elections:
    build:
      context: ./services/elections
      dockerfile: Dockerfile-prod
    expose:
      - '5000'
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@elections-db:5432/elections_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@elections-db:5432/elections_test
    depends_on:
      - elections-db

  elections-db:
    build:
      context: ./services/elections/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - elections
