version: '3.7'

services:

  elections:
    build:
      context: ./services/elections
      dockerfile: Dockerfile-dev
    volumes:
      - './services/elections:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig